name: "Build Gradle project"
on: [ push, pull_request, workflow_dispatch ]

jobs:
    build:
        name: Test JVM/Gradle (${{ matrix.java-version }}, ${{ matrix.gradle-version }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java-version: [ 8, 11, 16, 17 ]
                gradle-version: [ 7.0.2, 7.2, 7.3.3, 7.6-20221024231219+0000 ]
        steps:
            - name: Check out project
              uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: 11
                  distribution: 'liberica'
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Build with Gradle
              run: ./gradlew clean build -PtestJavaRuntimeVersion=${{ matrix.java-version }} -PtestGradleVersion=${{ matrix.gradle-version }}
              env:
                  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
