name: "Build Gradle project"
on: [ push, workflow_dispatch ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java-version: [ 8, 11, 16 ]
                gradle-version: [ 7.1.1, 7.2 ]
        name: Test JVM/Gradle (${{ matrix.java-version }}, ${{ matrix.gradle-version }})
        steps:
            -   name: Check out project
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: 11
            -   name: Build with Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: build -PtestJavaRuntimeVersion=${{ matrix.java-version }} -PtestGradleVersion=${{ matrix.gradle-version }} -Pgradle-plugindev-plugin.acceptGradleTOS=true

